#!/bin/bash
set -eou pipefail
set -x
ROOT=$(git rev-parse --show-toplevel)
cd "${ROOT}"

go test -covermode=atomic -coverpkg=./... -coverprofile cover.out -v -race -shuffle=on ./... && CGO_ENABLED=0 go tool cover -html cover.out -o cover.html && open cover.html